var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var collectionConstant = require('./../config/collectionConstant');

var subContractorSchema = new mongoose.Schema({
    company_id: { type: mongoose.ObjectId, default: "" },
    project_id: { type: mongoose.ObjectId, default: "" },
    is_delete: { type: Number, default: 0 },
});

var subContractorDefaultValue = {
    company_id: "",
    project_id: "",
    is_delete: 0,
};

var companySchema = new Schema({
    companyname: { type: String, default: "" },
    companywebsite: { type: String, default: "" },
    companyemail: { type: String, default: "" },
    companyphone: { type: String, default: "" },
    companyphone2: { type: String, default: "" },
    companyfax: { type: String, default: "" },
    companymobile: { type: String, default: "" },
    companystatus: { type: Number, default: 1 },
    companyaddress: { type: String, default: "" },
    companyaddresscity: { type: String, default: "" },
    companyaddressstate: { type: String, default: "" },
    companyaddresszip: { type: String, default: "" },
    companyein: { type: String, default: "" },
    companyvendor: { type: String, default: "" },
    companywhatsapp: { type: String, default: "" },
    companytwitter: { type: String, default: "" },
    companyinstagram: { type: String, default: "" },
    companyfacebook: { type: String, default: "" },
    conatactpersonname: { type: String, default: "" },
    conatactpersontitle: { type: String, default: "" },
    conatactpersonemail: { type: String, default: "" },
    conatactpersonphone1: { type: String, default: "" },
    conatactpersonphone2: { type: String, default: "" },
    conatactpersonwhatsapp: { type: String, default: "" },
    conatactpersoninstagram: { type: String, default: "" },
    conatactpersontwitter: { type: String, default: "" },
    conatactpersonfacebook: { type: String, default: "" },
    ccname: { type: String, default: "" },
    ccaddress: { type: String, default: "" },
    ccnumber: { type: String, default: "" },
    cc_cvv: { type: String, default: "" },
    ccexpiry: { type: String, default: "" },
    cccity: { type: String, default: "" },
    ccstate: { type: String, default: "" },
    cczipcode: { type: String, default: "" },
    billingpersonname: { type: String, default: "" },
    billingpersontitle: { type: String, default: "" },
    billingpersonemail: { type: String, default: "" },
    billingpersonphone: { type: String, default: "" },
    billingpersonaddress: { type: String, default: "" },
    billingpersoncity: { type: String, default: "" },
    billingpersonstate: { type: String, default: "" },
    billingpersonzipcode: { type: String, default: "" },
    added_by_role: { type: Number, default: 1 },
    added_by_id: { type: mongoose.ObjectId, default: "" },
    companycode: { type: String, default: "" },
    rovuk_type: { type: String, default: "" },
    companylogo: { type: String, default: "" },
    companyactivesince: { type: Number, default: 0 },
    companydivision: { type: [mongoose.ObjectId], default: [] },
    companysize: { type: mongoose.ObjectId, default: "" },
    companytype: { type: mongoose.ObjectId, default: "" },
    plan: { type: mongoose.ObjectId, default: "" },
    billingplan: { type: String, default: "" },
    otherstool: [{
        logo_url: { type: String, default: "" },
        key: { type: String, default: "" },
        value: { type: String, default: "" },
        login_url: { type: String, default: "" },
    }],
    companylanguage: { type: String, default: "" },
    naicscode: { type: mongoose.ObjectId, default: "" },
    created_at: { type: Number, default: 0 },
    created_by: { type: mongoose.ObjectId, default: "" },
    updated_at: { type: Number, default: 0 },
    updated_by: { type: mongoose.ObjectId, default: "" },
    is_delete: { type: Number, default: 0 },

    parent_company: { type: subContractorSchema, default: subContractorDefaultValue },
    sub_contractor_company: { type: [subContractorSchema], default: [] },

    invoice_user: [{
        user_id: { type: mongoose.ObjectId, default: "" },
        useremail: { type: String, default: "" },
        password: { type: String, default: "" },
        userstatus: { type: Number, default: 1 },
        is_delete: { type: Number, default: 0 },
    }],
    grid_user: [{
        user_id: { type: mongoose.ObjectId, default: "" },
        useremail: { type: String, default: "" },
        password: { type: String, default: "" },
        userstatus: { type: Number, default: 1 },
        is_delete: { type: Number, default: 0 },
    }],
}, { collection: collectionConstant.SUPER_ADMIN_COMPANY, timestamps: true });

module.exports = companySchema;