module.exports = {
    SUPPLIER_EMAIL_TEMPLATE_HISTORY: "supplier_email_template_histories",
    USER_HISTORY: "users_histories",
    EMERGENCY_CONTACT_HISTORY: "emergency_contacts_histories",
    USERDOCUMENT_HISTORY: "usersdocument_histories",
    VENDOR_USER_HISTORY: "ocpr_vendor_user_histories",
    SUPPLIER_PROJECT_HISTORY: "supplier_projects_histories",
    SUPPLIER_VENDOR_PERFORMANCE_HISTORY: "supplier_vendor_performance_histories",
    SUPPLIER_CHANGE_ORDER_HISTORY: "supplier_change_order_histories",
    SUPPLIER_PROJECT_USER_HISTORY: "supplier_project_users_histories",
    SUPPLIER_PAYMENT_RETAINAGE_HISTORY: "supplier_payment_retainage_histories",
    SUPPLIER_VENDOR_NOTE_HISTORY: "supplier_vendor_note_histories",
    SUPPLIER_OWNER_DIRECT_PURCHASE_HISTORY: "supplier_owner_direct_purchase_histories",
    SUPPLIER_PAYMENT_HISTORY: "supplier_payment_histories",
    SUPPLIER_CONTRACT_HISTORY: "supplier_contract_histories",
    LOCATIONS_HISTORY: "locations_histories",
    SUPPLIER_PROJECT_CERTIFICATE_HISTORY: "supplier_project_certificate_histories",
    SUPPLIER_CONTRACT_DOCUMENT_HISTORY: "supplier_contract_document_histories",
    SUPPLIER_SCHEDULE_OF_ITEM_HISTORY: "supplier_schedule_of_item_histories",
    SUPPLIER_SCHEDULE_OF_ITEM_TASK_HISTORY: "supplier_schedule_of_item_task_histories",
    SETTINGS_HISTORY: "setting_histories",
    INVOICES_HISTORY: "invoice_histories",
    VENDOR_HISTORY: "vendor_history",
    TEMPLATE_HISTORY: "template_history",

    INVOICE_SETTINGS_HISTORY: "invoice_setting_histories",
    INVOICE_USER_HISTORY: "invoice_user_histories",
    INVOICE_USER_DOCUMENT_HISTORY: "invoice_user_document_histories",
    INVOICE_VENDOR_HISTORY: "invoice_vendor_histories",
    INVOICE_CLIENT_HISTORY: "invoice_client_histories",

    AP_INVOICE_HISTORY: 'ap_invoice_histories',
};