export enum WEB_ROUTES {
  SIDEMENU_DASHBOARD = 'dashboard',
  SIDEMENU_VENDOR = 'vendor',
  SIDEMENU_CLIENT = 'client',
  SIDEMENU_INVOICE = 'invoice',
  SIDEMENU_DOCUMENTS = 'documents',
  SIDEMENU_REPORTS = 'reports',
  SIDEMENU_USER = 'user',
  SIDEMENU_SETTINGS = 'settings',

  LOGIN = '/authentication',

  FORM = 'form',
  VIEW = 'view',
  HISTORY = 'history',
  GRID = 'grid',
  CLIENT = '/client',
  VENDOR = '/vendor',
  USER = '/user',
  INVOICE = '/invoice',
  DOCUMENTS = '/documents',
  REPORTS = '/reports',
  DETAILS = 'details',
  MESSAGES = 'messages',
  MESSAGE_VIEW = 'message-view',
  VIEW_DOCUMENT = 'view-document',
  USER_EMERGENCY_CONTACT = 'emergency-contact',
  USER_DOCUMENT = 'document',

  DOCUMENT_UNKNOWN_TYPE = '/documents/unknown-document',

  DASHBOARD = '/dashboard',
  MONTHLY_HISTORY = 'monthly-history',
  MONTHLY_INVOICE = 'monthly-invoice',
  DUPLICATE_DOCUMENTS = 'duplicate-documents',
  DASHBOARD_MONTHLY_HISTORY = '/dashboard/monthly-history',
  DASHBOARD_MONTHLY_INVOICE = '/dashboard/monthly-invoice',
  DASHBOARD_DUPLICATE_DOCUMENTS = '/dashboard/duplicate-documents',

  FORCEFULLY_CHANGE_PASSWORD = '/authentication/forcefully-change-password',
  CHANGE_PASSWORD = '/authentication/change-password',
  FORGOT_PASSWORD = '/authentication/forgot-password',

  SEND_OTP = '/authentication/send-otp',

  CLIENT_FORM = '/client/form',
  CLIENT_HISTORY = '/client/history',

  VENDOR_FORM = '/vendor/form',
  VENDOR_ARCHIVE = '/vendor/archive',
  VENDOR_HISTORY = '/vendor/history',
  VENDOR_GRID = '/vendor/grid',
  USER_GRID = '/user/grid',
  USER_HISTORY = '/user/history',
  USER_FORM = '/user/form',
  USER_EMERGENCY_CONTACT_FORM = '/user/emergency-contact/form',
  USER_DOCUMENT_FORM = '/user/document/form',

  COMPANY_INFO_FORM = 'company-info-form',

  INVOICE_DETAILS = '/invoice/details',
  INVOICE_VIEW_DOCUMENT = '/invoice/view-document',
  INVOICE_MESSAGES = '/invoice/messages',
  INVOICE_MESSAGE_VIEW = '/invoice/message-view',
  INVOICE_HISTORY = '/invoice/history',

  VIEW_REPORT = 'reports/view',

  MAILBOX_SETTING = '/settings/mailbox',
  MAILBOX_FOR_SETTING = '/settings/mailbox-form',
  EMPLOYEE_SETTING = '/settings/employeesettings',
  ROLE_SETTING = '/settings/rolesettings',
  ALERT_SETTING = '/settings/alerts',
  SMTP_SETTING = '/settings/smtp',
  INTEGRATION_SETTING = '/settings/integration',
  QBO_INTEGRATION_SETTING = '/settings/qbo-integration',
  QBD_INTEGRATION_SETTING = '/settings/qbd-integration',
  USAGE_SETTING = '/settings/usage',
  OTHER_SETTING = '/settings/othersettings',
  SECURITY_SETTING = '/settings/security',
  COSTCODE_SETTING = '/settings/costcode',
  DOCUMENT_VIEW_SETTING = '/settings/documentview',
  COMPANY_INFO_FORM_SETTING = '/settings/company-info-form',
}
